# The Database type
# Options: mysql, sqlite
db_type: "mysql"

# You can ignore this when you use sqlite.
mysql:
  username: "example"
  password: "yourpassword"
  port: 3306
  database: "lachmoney"
  host: "example.com"

# Define the filename if you use sqlite.
sqlite:
  file: "database.db"